const WeatherActionTypes = {
  FETCH_CURR_WEATHER_START: 'FETCH_CURR_WEATHER_LOCATION_START',
  FETCH_CURR_WEATHER_SUCCESS: 'FETCH_CURR_WEATHER_LOCATION_SUCCESS',
  FETCH_CURR_WEATHER_FAILURE: 'FETCH_CURR_WEATHER_LOCATION_FAILURE',
  GET_CURR_COORDS_START: 'GET_CURR_COORDS_START',
  GET_CURR_COORDS_SUCCESS: 'GET_CURR_COORDS_SUCCESS',
  GET_CURR_COORDS_FAILURE: 'GET_CURR_COORDS_FAILURE',
};

export default WeatherActionTypes;
